#
# MPI multiprecision maths library (from gpg)
#

obj-$(CONFIG_CRYPTO_MPILIB) = \
	generic_mpih-lshift.o		\
	generic_mpih-mul1.o		\
	generic_mpih-mul2.o		\
	generic_mpih-mul3.o		\
	generic_mpih-rshift.o		\
	generic_mpih-sub1.o		\
	generic_mpih-add1.o		\
	generic_udiv-w-sdiv.o		\
	mpicoder.o			\
	mpi-add.o			\
	mpi-bit.o			\
	mpi-div.o			\
	mpi-cmp.o			\
	mpi-gcd.o			\
	mpih-cmp.o			\
	mpih-div.o			\
	mpih-mul.o			\
	mpi-inline.o			\
	mpi-inv.o			\
	mpi-mpow.o			\
	mpi-mul.o			\
	mpi-pow.o			\
	mpi-scan.o			\
	mpiutil.o

