#ifndef _ASM_GENERIC_KEXEC_H
#define _ASM_GENERIC_KEXEC_H

#ifdef CONFIG_KEXEC_AUTO_RESERVE

#ifndef KEXEC_AUTO_RESERVED_SIZE
#define KEXEC_AUTO_RESERVED_SIZE (1ULL<<27) /* 128M */
#endif
#ifndef KEXEC_AUTO_THRESHOLD
#define KEXEC_AUTO_THRESHOLD (1ULL<<31) /* 2G */
#endif


#endif /* CONFIG_KEXEC_AUTO_RESERVE */

#endif
